spring.application.name=AdotaPet

spring.datasource.url=jdbc:mysql://localhost:3306/adotapet?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=SafiraRuby
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always